# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore
  exclude:
    - "**/*.freezed.dart"
    - "**/*.g.dart"

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - avoid_print
    - require_trailing_commas
    - prefer_single_quotes
    - sort_child_properties_last
    - use_key_in_widget_constructors
    - sized_box_for_whitespace
    - avoid_unnecessary_containers
    - prefer_is_empty
    - prefer_is_not_empty
    - unnecessary_string_interpolations
    - no_leading_underscores_for_local_identifiers
